services:
  - type: web
    name: acquasystems
    runtime: static
    buildCommand: ""
    staticPublishPath: ./public
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html